Repository team-MUMENT/MUMENT-SERVER, pull requests merged in 2022-12, with the labels that each got.

#80 [ADD] 카카오 로그인 관련 라이브러리, JWT 토큰 관련 라이브러리 추가
  src/interfaces/auth/JwtPayload.ts
  src/library/jwtHandler.ts
  src/library/kakaoAuth.ts
  src/modules/serviceReturnConstant.ts
  yarn.lock
Labels: 🌊유정🌊, ADD

#84 [FEAT] 카카오 로그인
  src/interfaces/auth/AuthTokenResponseDto.ts
  src/interfaces/auth/JwtPayload.ts
  src/interfaces/user/UserInfoRDB.ts
  src/modules/db/Auth.ts
  src/modules/serviceReturnConstant.ts
  src/services/AuthService.ts
Labels: 🌊유정🌊, FEAT

#86 [REFACTOR] 보관함 좋아요한 뮤멘트 리스트 - sql query 사용 로직으로 변경 & 뮤멘트 기록하기에서 Music DB에 검색&저장 하도록 변경
  src/interfaces/mument/MumentCreateDto.ts
  src/interfaces/mument/MyMumentInfoRDB.ts
  src/modules/cardTagList.ts
  src/modules/db/Mument.ts
  src/modules/db/Music.ts
  src/modules/db/User.ts
  src/services/AuthService.ts
  src/services/MumentService.ts
  src/services/UserService.ts
Labels: 🎶채은🎶
