Repository team-MUMENT/MUMENT-SERVER, pull requests merged in 2022-07, with the labels that each got.

#8 [CHORE] eslint 오류 해결 및 lint 적용
  .eslintrc.json
  .prettierrc.json
  src/config/index.ts
  src/controllers/MumentController.ts
  src/controllers/MusicController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/index.ts
  src/interfaces/like/LikeInfo.ts
  src/interfaces/mument/MumentInfo.ts
  src/interfaces/music/MusicInfo.ts
  src/interfaces/user/UserInfo.ts
  src/loaders/db.ts
  src/models/Like.ts
  src/models/Mument.ts
  src/models/Music.ts
  src/models/User.ts
  src/modules/responseMessage.ts
  src/modules/statusCode.ts
  src/modules/util.ts
  src/routes/MumentRouter.ts
  src/routes/MusicRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: 🌊유정🌊, CHORE

#11 [FEAT] 곡 상세보기 구현
  src/controllers/MusicController.ts
  src/interfaces/music/MusicMumentListResponseDto.ts
  src/interfaces/music/MusicMyMumentResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/MusicRouter.ts
  src/services/MusicService.ts
Labels: 🌊유정🌊, FEAT

#18 [CHORE] 뮤멘트 카드뷰 인터페이스 통일
  src/interfaces/mument/MumentCardViewInterface.ts
  src/interfaces/music/MusicMumentListResponseDto.ts
  src/interfaces/music/MusicMyMumentResponseDto.ts
  src/routes/MumentRouter.ts
Labels: 🌊유정🌊, CHORE

#20 [FEAT] 히스토리 조회 구현
  src/controllers/MumentController.ts
  src/interfaces/mument/MumentHistoryResponseDto.ts
  src/interfaces/mument/MumentInfo.ts
  src/modules/responseMessage.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT

#23 [FEAT] 좋아요 기능 구현
  src/controllers/MumentController.ts
  src/interfaces/like/LikeCountResponseDto.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT, ADD

#31 [FEAT] 뮤멘트 수정하기 구현 #27
  src/controllers/MumentController.ts
  src/modules/responseMessage.ts
  src/routes/MumentRouter.ts
  src/routes/UserRouter.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
  src/services/UserService.ts
  yarn.lock
Labels: 🎶채은🎶, ✨UPDATE

#37 [DEPLOY] 1차 배포를 위한 merge
  .eslintrc.json
  .prettierrc.json
  README.md
  src/config/index.ts
  src/controllers/MumentController.ts
  src/controllers/MusicController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/index.ts
  src/interfaces/common/PostBaseResponseDto.ts
  src/interfaces/like/LikeCountResponseDto.ts
  src/interfaces/like/LikeInfo.ts
  src/interfaces/mument/IsFirstResponseDto.ts
  src/interfaces/mument/MumentCardViewInterface.ts
  src/interfaces/mument/MumentCreateDto.ts
  src/interfaces/mument/MumentHistoryResponseDto.ts
  src/interfaces/mument/MumentInfo.ts
  src/interfaces/mument/MumentResponseDto.ts
  src/interfaces/music/MusicInfo.ts
  src/interfaces/music/MusicMumentListResponseDto.ts
  src/interfaces/music/MusicMyMumentResponseDto.ts
  src/interfaces/music/MusicResponseDto.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserMumentListResponseDto.ts
  src/interfaces/user/UserResponseDto.ts
  src/loaders/db.ts
  src/models/Like.ts
  src/models/Mument.ts
  src/models/Music.ts
  src/models/User.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/modules/statusCode.ts
  src/routes/MumentRouter.ts
  src/routes/MusicRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
  src/services/UserService.ts
  src/services/index.ts
  yarn.lock
Labels: 🚀DEPLOY

#39 [HOTFIX] Typescript 에러 해결 #38
  src/controllers/MumentController.ts
  src/controllers/MusicController.ts
  src/interfaces/music/MusicMyMumentResponseDto.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
Labels: 🔥HOTFIX, 🚀DEPLOY

#40 [HOTFIX] Typescript 에러 해결 #38
  src/interfaces/mument/MumentCardViewInterface.ts
  src/services/MusicService.ts
Labels: 🔥HOTFIX

#41 [HOTFIX] 라우터 오타 수정
  src/routes/UserRouter.ts
Labels: 🔥HOTFIX

#45 [REFACTOR] auth 라우터 분리
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/models/againSelection.ts
  src/models/bannerSelection.ts
  src/models/homeCandidate.ts
  src/models/todaySelection.ts
  src/routes/AuthRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: 🌊유정🌊, REFACTOR, 🔥HOTFIX

#46 [FEAT] 랜덤 뮤멘트 조회 로직 구현
  src/controllers/MumentController.ts
  src/interfaces/home/AgainSelectionInfo.ts
  src/interfaces/home/BannerSelectionInfo.ts
  src/interfaces/home/HomeCandidateInfo.ts
  src/interfaces/home/RandomMumentInterface.ts
  src/interfaces/home/TodaySelectionInfo.ts
  src/interfaces/mument/RandomMumentResponeDto.ts
  src/loaders/db.ts
  src/models/againSelection.ts
  src/models/bannerSelection.ts
  src/models/homeCandidate.ts
  src/models/todaySelection.ts
  src/modules/responseMessage.ts
  src/modules/tagTitle.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT, ✨READ

#48 [FEAT] 오늘의 뮤멘트 조회 구현
  src/controllers/MumentController.ts
  src/interfaces/mument/TodayMumentResponseDto.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT

#50 [FEAT] 배너 조회 구현
  src/controllers/MumentController.ts
  src/interfaces/mument/TodayBannerResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT

#52 [FEAT] 다시 들은 곡의 뮤멘트 조회 구현
  src/controllers/MumentController.ts
  src/interfaces/mument/AgainMumentResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, FEAT

#60 [ADD] 슬랙 웹훅 코드 추가
  package.json
  src/config/index.ts
  src/controllers/AuthController.ts
  src/controllers/MumentController.ts
  src/controllers/MusicController.ts
  src/controllers/UserController.ts
  src/library/slackWebhook.ts
  src/services/MusicService.ts
  yarn.lock
Labels: 🌊유정🌊, ADD
