Repository team-MUMENT/MUMENT-SERVER, pull requests merged in 2023-01, with the labels that each got.

#90 [REFACTOR] request-header에서 token 받아서 user 객체 id 반환하는 미들웨어 생성 & 기존 채은 담당 api 모두 토큰 교체 완료
  src/config/index.ts
  src/controllers/MumentController.ts
  src/controllers/UserController.ts
  src/index.ts
  src/interfaces/auth/JwtPayload.ts
  src/interfaces/user/UserInfoRDB.ts
  src/library/jwtHandler.ts
  src/middlewares/auth.ts
  src/modules/responseMessage.ts
  src/routes/MumentRouter.ts
  src/routes/UserRouter.ts
  src/services/MumentService.ts
  src/services/UserService.ts
Labels: 🎶채은🎶

#93 [REFACTOR] 좋아요, 히스토리 조회 리팩토링
  src/controllers/MumentController.ts
  src/interfaces/like/LikeCountResponseDto.ts
  src/interfaces/mument/MumentCardViewInterface.ts
  src/interfaces/mument/MumentHistoryResponseDto.ts
  src/modules/serviceReturnConstant.ts
  src/routes/MumentRouter.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, REFACTOR

#112 [REFACTOR, FEAT] 기존 API 리팩토링 & 새로운 API 개발 & jwt handler 관련 수정
  package.json
  src/config/index.ts
  src/config/s3Config.ts
  src/controllers/AuthController.ts
  src/controllers/MumentController.ts
  src/controllers/MusicController.ts
  src/controllers/UserController.ts
  src/interfaces/music/MusicMyMumentResponseDto.ts
  src/interfaces/music/MusicResponseDto.ts
  src/interfaces/user/UserDeleteResponseDto.ts
  src/interfaces/user/UserLeaveResponseDto.ts
  src/interfaces/user/UserProfileSetResponseDto.ts
  src/interfaces/user/UserResponseDto.ts
  src/library/jwtHandler.ts
  src/middlewares/auth.ts
  src/middlewares/uploadImage.ts
  src/modules/db/Mument.ts
  src/modules/db/Music.ts
  src/modules/db/User.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/routes/AuthRouter.ts
  src/routes/MumentRouter.ts
  src/routes/MusicRouter.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
  src/services/UserService.ts
  yarn.lock
Labels: 🌊유정🌊

#115 [FEAT] 프로필 설정 완료 조회 API & [MOD] 차단 관련 로직 추가
  dist/interfaces/like/LikeInfo.js
  dist/interfaces/like/LikeInfo.js.map
  dist/interfaces/mument/MumentInfo.js
  dist/interfaces/mument/MumentInfo.js.map
  dist/interfaces/music/MusicInfo.js
  dist/interfaces/music/MusicInfo.js.map
  dist/interfaces/user/UserInfo.js
  dist/interfaces/user/UserInfo.js.map
  dist/models/AgainSelection.js
  dist/models/AgainSelection.js.map
  dist/models/BannerSelection.js
  dist/models/BannerSelection.js.map
  dist/models/HomeCandidate.js
  dist/models/HomeCandidate.js.map
  dist/models/Like.js
  dist/models/Like.js.map
  dist/models/Mument.js
  dist/models/Mument.js.map
  dist/models/Music.js
  dist/models/Music.js.map
  dist/models/TodaySelection.js
  dist/models/TodaySelection.js.map
  dist/modules/dummyData.js
  dist/modules/dummyData.js.map
  src/controllers/MumentController.ts
  src/controllers/UserController.ts
  src/modules/db/User.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/routes/MumentRouter.ts
  src/routes/UserRouter.ts
  src/services/MumentService.ts
  src/services/MusicService.ts
Labels: 🌊유정🌊, FEAT, MOD

#123 [MOD] 카카오 로그인, 프로필 설정 관련 수정
  src/controllers/UserController.ts
  src/library/jwtHandler.ts
  src/middlewares/auth.ts
  src/modules/responseMessage.ts
  src/modules/serviceReturnConstant.ts
  src/services/AuthService.ts
  src/services/UserService.ts
Labels: 🌊유정🌊, MOD

#125 [FIX] 토큰 만료시 의도한 메세지가 뜨지 않는 에러 수정
  src/library/jwtHandler.ts
Labels: FIX

#128 [REFACTOR] 홈화면 API 리팩토링
  dist/controllers/MumentController.js
  dist/controllers/MumentController.js.map
  dist/services/MumentService.js
  dist/services/MumentService.js.map
  src/controllers/MumentController.ts
  src/interfaces/home/AgainSelectionInfo.ts
  src/interfaces/home/BannerSelectionInfo.ts
  src/interfaces/home/RandomMumentInterface.ts
  src/interfaces/home/TodaySelectionInfo.ts
  src/interfaces/mument/AgainMumentResponseDto.ts
  src/interfaces/mument/TodayMumentResponseDto.ts
  src/services/MumentService.ts
Labels: 🌊유정🌊, REFACTOR

#129 [MOD] 쿼리문 조건 추가 및 boolean값 리턴하도록 수정
  dist/services/MumentService.js
  dist/services/MumentService.js.map
  src/services/MumentService.ts
Labels: 🌊유정🌊, MOD

#130 [MOD] 쿼리문에 id 추가
  dist/services/MumentService.js
  src/services/MumentService.ts
Labels: 🌊유정🌊, MOD

#131 [MOD] 모든 뮤멘트 조회 에러 수정 및 홈 API 리턴 타입 변경
  dist/services/MumentService.js
  dist/services/MumentService.js.map
  dist/services/MusicService.js
  dist/services/MusicService.js.map
  src/services/MumentService.ts
  src/services/MusicService.ts
Labels: 🌊유정🌊, MOD
